#!/usr/bin/env python
# encoding: utf-8
#
# module author: subinacls
#


{"piipci":{
	"sex": [
	    "m",
	    "male",
	    "f",
	    "female"
	],
	"fullname": {
	    "male": {
	        "first": [
				"rick",
	            "dave",
	            "mike"
	        ],
	        "middle": [
		        "scott",
	            "john",
	            "jim"
	        ],
	        "last": [
		        "jhonson",
	            "smith"
	        ],
	        "title": [
		        "mr. ",
	            "master ",
	            "sr. ",
	            "jr. ",
	            "sir "
	        ]
	    },
	    "female": {
	        "first": [
		        "mary",
	            "susan",
	            "grace"
	        ],
	        "middle": [
		        "jane",
	            "jamie",
	            "erin"
	        ],
	        "last": [
				"jhonson",
	            "smith"
	        ],
	        "title": [
				"mrs. ",
	            "miss ",
	            "ms. ",
	            "lady "
	        ]
	    }
	},
	"ssn": [
	    "219-09-9999",
	    "078-05-1120",
	    "219099999",
	    "078051120"
	],
	"telephone": [
	    "1-999-555-5555",
	    "19995555555",
	    "9995555555",
	    "19998675309"
	],
	"creditcard": [
	    "0400-0000-0000-0000",
	    "0400000000000000",
	    "4242424242424242",
	    "4012888888881881",
	    "4000056655665556",
	    "5555555555554444",
	    "5200828282828210",
	    "5105105105105100",
	    "378282246310005",
	    "371449635398431",
	    "6011111111111117",
	    "6011000990139424",
	    "30569309025904",
	    "38520000023237",
	    "3530111333300000",
	    "3566002020360505",
	    "4242-4242-42424242",
	    "4012-8888-8888-1881",
	    "4000-0566-5566-5556",
	    "5555-5555-5555-4444",
	    "5200-8282-8282-8210",
	    "5105-1051-0510-5100",
	    "3782-8224-6310-005",
	    "3714-4963-5398-431",
	    "6011-1111-1111-1117",
	    "6011-0009-9013-9424",
	    "3056-9309-0259-04",
	    "3852-0000-0232-37",
	    "3530-1113-3330-0000",
	    "3566-0020-2036-0505"
	],
	"cvv": [
	    "123",
	    "456"
	],
	"passport": {
	    "country": "example"
	},
	"drvlicense": {
	    "state": "example"
	},
	"fedtaxid": [
	    "example"
	],
	"medinfo":[
		"example format construction"
	],
	"bankaccount": {
	    "routing": [
	        "example"
	    ],
	    "accountnum": [
	        "example"
	    ]
	},
	"911addrgen": {
	    "state": {
	        "Alabama": [
	        ],
	        "Alaska": [
	        ],
	        "Arizona": [
	        ],
	        "Arkansas": [
	        ],
	        "California": [
	        ],
	        "Colorado": [
	        ],
	        "Connecticut": [
	        ],
	        "Delaware": [
	        ],
	        "Florida": [
		        "apopka, fl 32703",
	            "orlando, fl 32765"
	        ],
	        "Georgia": [
	        ],
	        "Hawaii": [
	        ],
	        "Idaho": [
	        ],
	        "Illinois": [
	        ],
	        "Indiana": [
	        ],
	        "Iowa": [
	        ],
	        "Kansas": [
	        ],
	        "Kentucky": [
	        ],
	        "Louisiana": [
	        ],
	        "Maine": [
	        ],
	        "Maryland": [
	        ],
	        "Massachusetts": [
	        ],
	        "Michigan": [
	        ],
	        "Minnesota": [
	        ],
	        "Mississippi": [
	        ],
	        "Missouri": [
	        ],
	        "Montana": [
	        ],
	        "Nebraska": [
	        ],
	        "Nevada": [
	        ],
	        "New Hampshire": [
	        ],
	        "New Jersey": [
	        ],
	        "New Mexico": [
	        ],
	        "New York": [
	        ],
	        "North Carolina": [
	        ],
	        "North Dakota": [
	        ],
	        "Ohio": [
	        ],
	        "Oklahoma": [
	        ],
	        "Oregon": [
	        ],
	        "Pennsylvania": [
	        ],
	        "Rhode Island": [
	        ],
	        "South Carolina": [
	        ],
	        "South Dakota": [
	        ],
	        "Tennessee": [
	        ],
	        "Texas": [
	        ],
	        "Utah": [
	        ],
	        "Vermont": [
	        ],
	        "Virginia": [
	        ],
	        "Washington": [
	        ],
	        "West Virginia": [
	        ],
	        "Wisconsin": [
	        ],
	        "Wyoming": [
	        ]
	    },
	    "streetname": [
	        "pentest"
	    ],
	    "stprefix": [
	        " .dr",
	        " .st",
	        " .way",
	        " .rd"
	    ],
	    "stpostfix": [
	        "north ",
	        "south ",
	        "east ",
	        "west ",
	        "nw ",
	        "ne ",
	        "sw ",
	        "se "
	    ],
	    "country": [
	        "USA",
	        "America"
	    ],
	    "aptnum": [
	        "apt. 101"
	    ]
	},
	"emailaddr": [
	    "someuser@aol.com"
	],
	"ipaddr": {
	    "external": [
	        "8.8.8.8"
	    ],
	    "internal": [
	        "192.168.0.1"
	    ]
	},
	"macaddr": [
	    "00:00:00:00:00:00"
	],
	"carinfo": {
	    "make": [
	        "Alcre",
	        "Anasagasti",
	        "Arbus",
	        "Autoar",
	        "Cametal",
	        "Crespi",
	        "De Carlo",
	        "Dinarg",
	        "Dinborg",
	        "El Detalle Vehículos",
	        "Eniak",
	        "Feresa",
	        "Ferroni",
	        "Grosspal",
	        "Hispano-Argentina",
	        "IAMA",
	        "IES",
	        "Industria Mecánica Riojana",
	        "IAME",
	        "IKA",
	        "RYCSA",
	        "SIAM Di Tella",
	        "TATSA",
	        "Zanello",
	        "Elfin",
	        "FPV",
	        "Holden",
	        "HSV",
	        "Redback",
	        "Austro-Daimler",
	        "Austro-Fiat",
	        "Austro-Tatra",
	        "Denzel",
	        "Felber",
	        "KTM",
	        "Libelle",
	        "Lohner-Porsche",
	        "Magna Steyr",
	        "Möve",
	        "Puch",
	        "Steyr-Daimler-Puch",
	        "Atlas.",
	        "Bangladesh Machine Tools Factory",
	        "HPM",
	        "HS Enterprise",
	        "RUNNER",
	        "Singer Bangladesh",
	        "Walton",
	        "Auto-Mixte",
	        "Gillet",
	        "Nagant",
	        "Pieper",
	        "Agrale",
	        "Lobini",
	        "TAC",
	        "Troller",
	        "Gurgel",
	        "Puma",
	        "Litex",
	        "Angkor",
	        "Allard",
	        "Bombardier",
	        "Campagna",
	        "Conquest",
	        "Dupont",
	        "Dynasty",
	        "Foremost",
	        "HTT",
	        "Intermeccanica",
	        "Magnum",
	        "New Flyer",
	        "Nova Bus",
	        "Prevost",
	        "Super 7",
	        "Terradyne",
	        "ZENN",
	        "Acadian",
	        "Atlas",
	        "Bricklin",
	        "Brooks",
	        "Derby",
	        "Galt",
	        "Gray-Dort",
	        "Manic",
	        "McKay",
	        "McLaughlin",
	        "Meteor",
	        "Orion",
	        "Redpath",
	        "Russell",
	        "Studebaker",
	        "Tudhope",
	        "Baolong",
	        "Foton",
	        "Gonow",
	        "Great Wall",
	        "Liming",
	        "Wuling",
	        "Zhonghua",
	        "Crobus",
	        "DOK-ING",
	        "Rimac",
	        "Aero",
	        "Avia",
	        "Kaipan",
	        "Praga",
	        "Skoda",
	        "Tatra",
	        "Zenvo",
	        "Aérocarène",
	        "Aixam",
	        "Alpine",
	        "Bollore",
	        "Bugatti",
	        "Citroen",
	        "Exagon",
	        "Hommell",
	        "Ligier",
	        "Matra",
	        "Microcar",
	        "MDI",
	        "Peugeot",
	        "PGO",
	        "Renault",
	        "Venturi",
	        "Audi",
	        "Bitter",
	        "BMW",
	        "Büssing",
	        "Gumpert",
	        "MAN",
	        "Mercedes-Benz",
	        "Multicar",
	        "Neoplan",
	        "NSU",
	        "Opel",
	        "Porsche",
	        "Robur",
	        "Volkswagen",
	        "Wiesmann",
	        "Adler",
	        "AGA",
	        "AWZ",
	        "Barkas",
	        "Borgward",
	        "Brennabor",
	        "DKW",
	        "Glas",
	        "Goliath",
	        "Hansa",
	        "Heinkel",
	        "Horch",
	        "Karmann",
	        "Lloyd",
	        "Maybach",
	        "Messerschmitt",
	        "NAG",
	        "Simson",
	        "Tempo",
	        "Trabant",
	        "Wanderer",
	        "Wartburg",
	        "Attica",
	        "ABI",
	        "AMW",
	        "Ashok Leyland",
	        "Bajaj",
	        "Bharat",
	        "Chinkara",
	        "DC",
	        "Eicher",
	        "Escorts",
	        "Force",
	        "Hero",
	        "Hindustan",
	        "ICML",
	        "Mahindra",
	        "Maruti Suzuki",
	        "Premier",
	        "Royal Enfield",
	        "San",
	        "Swaraj",
	        "TAFE",
	        "Tata",
	        "TVS",
	        "Standard",
	        "Bahman",
	        "Iran Khodro",
	        "Kish Khodro",
	        "MVM",
	        "Pars Khodro",
	        "SAIPA",
	        "AIL",
	        "Autocars",
	        "Plasan",
	        "Abarth",
	        "Alfa Romeo",
	        "Autobianchi",
	        "Cizeta",
	        "De Tomaso",
	        "DR Motor",
	        "Ferrari",
	        "Fiat",
	        "Intermeccanica",
	        "Lamborghini",
	        "Lancia",
	        "Maserati",
	        "Pagani",
	        "Siata",
	        "Vignale",
	        "Acura",
	        "Daihatsu",
	        "Datsun",
	        "Dome",
	        "Hino",
	        "Honda",
	        "Infiniti",
	        "Isuzu",
	        "Lexus",
	        "Mazda",
	        "Mitsubishi",
	        "Mitsuoka",
	        "Nissan",
	        "Scion",
	        "Subaru",
	        "Suzuki",
	        "Toyota",
	        "Yamaha",
	        "Asahi",
	        "Ohta",
	        "Otomo",
	        "Prince",
	        "Tommykaira",
	        "Ford-Vairogs",
	        "Latvija",
	        "Bufori",
	        "Inokom",
	        "Naza",
	        "Perodua",
	        "Proton",
	        "DINA",
	        "Italika",
	        "Mastretta",
	        "Tranvias-Cimex",
	        "Vuhl",
	        "Ramirez",
	        "VAM",
	        "Venturi[1]",
	        "ABS",
	        "AllStoff",
	        "Alphax",
	        "Amfibug",
	        "APTS",
	        "Bikkel",
	        "Burton",
	        "Burtwell",
	        "Charon",
	        "Cygnus",
	        "Dakar",
	        "DAF",
	        "Donkervoort",
	        "Hansen",
	        "HB",
	        "Isis",
	        "KS",
	        "Le Patron",
	        "Motorious",
	        "Nova",
	        "Savage",
	        "Soleil",
	        "Spijkstaal",
	        "Spyker",
	        "Trigger",
	        "Vandenbrink",
	        "VDL Berkhof",
	        "Vencer",
	        "Voglietta",
	        "doorbreken",
	        "Anziel",
	        "Trekka",
	        "Arrinera",
	        "FSO",
	        "FSC Żuk",
	        "Syrena",
	        "Warszawa",
	        "ZSD Nysa",
	        "Vinci",
	        "Bravia",
	        "Portaro",
	        "UMM",
	        "Dacia",
	        "ROMAN",
	        "ARO",
	        "Oltcit",
	        "Rocar",
	        "UTB",
	        "Avtoframos",
	        "GAZ",
	        "IZh",
	        "Lada",
	        "Marussia",
	        "Moskvitch",
	        "Russo-Balt",
	        "UAZ",
	        "Yo-Mobile",
	        "ZiL",
	        "FAP",
	        "Ikarbus",
	        "IMT",
	        "Neobus",
	        "Zastava",
	        "Zoragy",
	        "Micro",
	        "Hyundai",
	        "Kia",
	        "Proto",
	        "Samsung",
	        "SsangYong",
	        "Daewoo",
	        "Abadal",
	        "GTA",
	        "Irizar",
	        "SEAT",
	        "Tauro",
	        "Tramontana",
	        "Esther",
	        "Koenigsegg",
	        "Jösse Car",
	        "Saab",
	        "Scania",
	        "Volvo",
	        "Enzmann",
	        "Monteverdi",
	        "Stealth",
	        "Sbarro",
	        "CMC",
	        "Luxgen",
	        "C-FEE",
	        "Cherdchai",
	        "Devs",
	        "Siam V.M.C.",
	        "Thai Rung",
	        "Wallyscar",
	        "Anadol",
	        "BMC",
	        "Guleryuz Karoseri",
	        "Hattat",
	        "Karsan",
	        "Otokar",
	        "Otosan",
	        "Oyak-Renault",
	        "Temsa",
	        "Tofaş-Fiat",
	        "Turk Traktor",
	        "ABA[2]",
	        "AC",
	        "Allard",
	        "Alvis",
	        "Armstrong Siddeley",
	        "Ascari",
	        "Aston Martin",
	        "Austin",
	        "Austin-Healey",
	        "BAC",
	        "Bentley",
	        "Bristol",
	        "British Leyland",
	        "Caterham",
	        "Daimler",
	        "Elva",
	        "Ginetta",
	        "GKD",
	        "Gordon Keeble",
	        "Grinnall",
	        "Hillman",
	        "Humber",
	        "Jaguar",
	        "Jensen",
	        "Jowett",
	        "Lanchester",
	        "Land Rover",
	        "Lister",
	        "Lotus",
	        "Marcos",
	        "McLaren",
	        "MG",
	        "Mini",
	        "Morgan",
	        "Morris",
	        "Noble",
	        "Riley",
	        "Rolls Royce",
	        "Rover",
	        "Singer",
	        "Standard",
	        "Sunbeam",
	        "Triumph",
	        "Trojan",
	        "TVR",
	        "Vauxhall",
	        "Wolseley",
	        "Buick",
	        "BXR",
	        "Cadillac",
	        "Callaway",
	        "Chevrolet",
	        "Chrysler",
	        "DeLorean",
	        "DiMora",
	        "Detroit Electric",
	        "Dodge",
	        "E-Z-GO",
	        "Falcon",
	        "Fisker",
	        "Ford",
	        "GEM",
	        "GMC",
	        "Hennessey",
	        "Iconic",
	        "International Harvester",
	        "Lucra",
	        "Jeep",
	        "Lincoln",
	        "Mosler",
	        "Navistar",
	        "Panoz",
	        "Ram",
	        "Rossion",
	        "Saleen",
	        "SSC",
	        "Tesla",
	        "Adams-Farwell",
	        "AMC",
	        "Apollo",
	        "Arrow",
	        "Auburn",
	        "Bates",
	        "Chandler",
	        "Cord",
	        "Crosley",
	        "Davis",
	        "Duesenberg",
	        "Eagle",
	        "Edsel",
	        "Essex",
	        "Frazer",
	        "Geo",
	        "Graham-Paige",
	        "Hummer",
	        "Hupmobile",
	        "Jeffery",
	        "Kaiser",
	        "Kissel",
	        "Laforza",
	        "LaSalle",
	        "Locomobile",
	        "Marmon",
	        "Mercury",
	        "Nash",
	        "Oldsmobile",
	        "Overland",
	        "Packard",
	        "Pierce-Arrow",
	        "Plymouth",
	        "Pontiac",
	        "Rambler",
	        "Regal",
	        "REO",
	        "Saturn",
	        "Stanley",
	        "Sterling",
	        "Studebaker",
	        "Tucker",
	        "TH!NK",
	        "Willys"
	    ],
	    "model": [
	        "Barchetta",
	        "Berlinetta",
	        "Box truck",
	        "Brougham",
	        "Buggy",
	        "Cab forward",
	        "Cabrio coach",
	        "Cabriolet (automobile)",
	        "Chassis cab",
	        "Close-coupled sedan",
	        "Coach convertible",
	        "Combi coupé",
	        "Convertible",
	        "Coupé",
	        "Coupe de Ville",
	        "Coupé utility",
	        "Crew cab",
	        "Drophead coupe",
	        "Drophead coupé",
	        "Dune buggy",
	        "Econobox",
	        "Fastback",
	        "Forecar",
	        "Full size van",
	        "Hackney carriage",
	        "Hardtop",
	        "H cont.",
	        "Hatchback",
	        "Hearse",
	        "Horse and buggy",
	        "High wheeler",
	        "Hot rod",
	        "Kammback",
	        "Kustom",
	        "Landau",
	        "Landaulet",
	        "Landyacht",
	        "Lead sled",
	        "Leisure activity vehicle",
	        "Limousine",
	        "Lowrider",
	        "Luton body",
	        "Minivan",
	        "Modified car",
	        "Notchback",
	        "Panel van",
	        "Phaeton body",
	        "Pickup truck",
	        "Quad coupé",
	        "Rat rod",
	        "Recreational vehicle",
	        "Roadster",
	        "Roadster utility",
	        "Roi-des-Belges",
	        "Roof module",
	        "Rumble seat",
	        "RV",
	        "Runabout",
	        "Sandrail",
	        "Sedan",
	        "Sedan delivery",
	        "Shave doors",
	        "Shooting-brake",
	        "Sound truck",
	        "Sport utility vehicle",
	        "Stanhope body",
	        "Station wagon",
	        "Swamp buggy",
	        "T-bucket",
	        "T-top",
	        "Targa top",
	        "Three window coupe",
	        "Three-box styling",
	        "Tonneau",
	        "Torpedo",
	        "Tourer",
	        "Touring car",
	        "Town car",
	        "Ute",
	        "Van",
	        "Vis-à-vis",
	        "Woodie"
	    ],
	    "year": [
	        "2050",
	        "2049",
	        "2048",
	        "2047",
	        "2046",
	        "2045",
	        "2044",
	        "2043",
	        "2042",
	        "2041",
	        "2040",
	        "2039",
	        "2038",
	        "2037",
	        "2036",
	        "2035",
	        "2034",
	        "2033",
	        "2032",
	        "2031",
	        "2030",
	        "2029",
	        "2028",
	        "2027",
	        "2026",
	        "2025",
	        "2024",
	        "2023",
	        "2022",
	        "2021",
	        "2020",
	        "2019",
	        "2018",
	        "2017",
	        "2016",
	        "2015",
	        "2014",
	        "2013",
	        "2012",
	        "2011",
	        "2010",
	        "2009",
	        "2008",
	        "2007",
	        "2006",
	        "2005",
	        "2004",
	        "2003",
	        "2002",
	        "2001",
	        "2000",
	        "1999",
	        "1998",
	        "1997",
	        "1996",
	        "1995",
	        "1994",
	        "1993",
	        "1992",
	        "1991",
	        "1990",
	        "1989",
	        "1988",
	        "1987",
	        "1986",
	        "1985",
	        "1984",
	        "1983",
	        "1982",
	        "1981",
	        "1980",
	        "1979",
	        "1978",
	        "1977",
	        "1976",
	        "1975",
	        "1974",
	        "1973",
	        "1972",
	        "1971",
	        "1970",
	        "1969",
	        "1968",
	        "1967",
	        "1966",
	        "1965",
	        "1964",
	        "1963",
	        "1962",
	        "1961",
	        "1960",
	        "1959",
	        "1958",
	        "1957",
	        "1956",
	        "1955",
	        "1954",
	        "1953",
	        "1952",
	        "1951",
	        "1950",
	        "1949",
	        "1948",
	        "1947",
	        "1946",
	        "1945",
	        "1944",
	        "1943",
	        "1942",
	        "1941"
	    ],
	    "vin": [
	        "123456789fgh63456789hi"
	    ],
	    "titlenumber": [
	        "432756437289543782"
	    ],
	    "regnum":[
	        "36547587543"
	    ]
	},
	"dob": {
	    "byear":{
	        "fdy":[
	            "2000"
	        ],
	        "tdy":[
	            "00"
	        ]
	    },
	    "bmonth": {
	        "cal": [
	            "January",
	            "Jan",
	            "February",
	            "Feb",
	            "March",
	            "Mar",
	            "April",
	            "May",
	            "June",
	            "July",
	            "August",
	            "Aug",
	            "October",
	            "Oct",
	            "September",
	            "Sept",
	            "November",
	            "Nov",
	            "December",
	            "Dec",
	        ],
	        "dcal": [
	            "01",
	            "02",
	            "03",
	            "04",
	            "05",
	            "06",
	            "07",
	            "08",
	            "09",
	            "10",
	            "11",
	            "12"
	        ]
	    },
	    "bdate": [
	        "1",
	        "2",
	        "3",
	        "4",
	        "5"
	    ]
	},
	"pob": [
	],
	"race": [
	    "white",
	    "African-American",
	    "Hispanic",
	    "Latino",
	    "Black",
	    "Asian",
	    "Native American"
	],
	"religion":[

	],
	"weight": [

	],
	"height": [

	],
	"haircolor": [

	],
	"eyecolor": [

	],
	"activities": [

	],
	"geolocal": [

	],
	"jodinfo": [

	],
	"education": [

	],
	"networth": [

	]
}
}